---
label: Site Configuration
hide_body: true
fields:
- type: text
  name: title
  label: Title
  description: Site title
  config:
    required: true
- type: text
  name: baseURL
  label: Base URL
  description: Hostname (and path) to the root
  hidden: true
- type: field_group
  name: params
  label: Params
  description: Site parameters
  config:
    required: true
  fields:
  - type: file
    name: favicon
    label: Favicon
    description: A square icon that represents your website
  - type: select
    name: palette
    label: Color Palette
    description: The color palette of the theme
    default: yellow
    config:
      required: true
      source:
        type: custom
      options:
      - yellow
      - blue
      - green
      - red
  - type: field_group
    name: header
    label: Header Configuration
    fields:
    - type: include
      name: include_header
      label: Header Configuration
      template: header
  - type: field_group
    name: footer
    label: Footer Configuration
    fields:
    - type: include
      name: include_footer
      label: Footer Configuration
      template: footer
- type: field_group
  name: taxonomies
  label: Taxonomies
  hidden: true
  fields:
  - type: text
    name: stub
    label: Stub
    hidden: true
    default: stub
    config:
      required: true
- type: list
  name: disableKinds
  label: Disable Kinds
  description: Enable disabling of all pages of the specified Kinds.
  hidden: true
  config:
    source:
      type: custom
    options:
    - page
    - home
    - section
    - taxonomy
    - taxonomyTerm
    - RSS
    - sitemap
    - robotsTXT
    - '404'
    use_select: true
- type: boolean
  name: uglyURLs
  label: Ugly URLs
  description: 'When enabled, creates URL of the form /filename.html instead of /filename/.'
  hidden: true
pages:
- config.yaml
